### ISSUE TITLE
gpu-access-sync CI is failing

### ISSUE THREAD

**Issue by sanjaysrikakulam** [usegalaxy-eu/gpu-access-sync#1]
For the last few months the CI is failing with the following error message

```
Traceback (most recent call last):
  File "process.py", line 75, in <module>
    add_users()
  File "process.py", line 72, in add_users
    gc.update_group(group_id=gpu_group["id"], user_ids=l_user_ids, role_ids=[gpu_role[1]["id"]])
  File "/scratch/shiningpanda/jobs/e3616bad/virtualenvs/d41d8cd9/lib/python3.8/site-packages/bioblend/galaxy/groups/__init__.py", line 105, in update_group
    return self._put(payload=payload, id=group_id)
  File "/scratch/shiningpanda/jobs/e3616bad/virtualenvs/d41d8cd9/lib/python3.8/site-packages/bioblend/galaxy/client.py", line 165, in _put
    return self.gi.make_put_request(url, payload=payload, params=params)
  File "/scratch/shiningpanda/jobs/e3616bad/virtualenvs/d41d8cd9/lib/python3.8/site-packages/bioblend/galaxyclient.py", line 198, in make_put_request
    raise ConnectionError("Unexpected HTTP status code: %s" % r.status_code,
bioblend.ConnectionError: Unexpected HTTP status code: 400: {"err_msg":"Input should be a valid string in ('body', 'name')","err_code":400008,"validation_errors":["{\"type\": \"string_type\", \"loc\": [\"body\", \"name\"], \"msg\": \"Input should be a valid string\", \"input\": null}"]}
```

1. This repo is using a really [old BioBlend version (0.11.0)](https://github.com/usegalaxy-eu/gpu-access-sync/blob/main/requirements.txt#L1).
2. The [`update_group` function](https://github.com/galaxyproject/bioblend/blob/9fcec8eb12bd08d5309509e74a9442091aafe272/bioblend/galaxy/groups/__init__.py#L95) accepts a `goup_name` arg, and if it is not provided, is set to `None` as the default
3. I guess Galaxy does not like this anymore since 24.0. As a result, do we see this error? 

@davelopez, I do not have experience with Galaxy API. Would you be willing to have a look or make suggestions?

**Comment by davelopez** [comment]
I'll investigate and report back :+1:

**Comment by sanjaysrikakulam** [comment]
Thank you!

**Comment by davelopez** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/18374 once it gets deployed :+1:

**Comment by sanjaysrikakulam** [comment]
Cool, thanks! Is it already synced with our branch?

**Comment by davelopez** [comment]
I don't think so, it was merged just one hour ago. Should I rebase or are you already on it @bgruening?

**Comment by sanjaysrikakulam** [comment]
If @bgruening has no objections, we should sync the changes (Monday).

**Comment by bgruening** [comment]
Its green again. Hopfeully it also works :)

Thanks @davelopez

**Comment by sanjaysrikakulam** [comment]
Cool, I will close this issue. Thanks @davelopez! :)
